[package]
name = "argh_shared"
version = "0.1.0"
authors = ["Taylor Cramer <cramertj@google.com>", "Benjamin Brittain<bwb@google.com>"]
edition = "2018"
license = "BSD License 2.0"
description = "Derive-based argument parsing optimized for code size"
repository = "https://github.com/google/argh"
